- provisioner.go
> Add tolerations to helper pod

- provisioner.go
MAY help https://github.com/rancher/local-path-provisioner/issues/14
> Increase the config file check interval to 30 seconds

- provisioner.go
https://github.com/rancher/local-path-provisioner/issues/22
> Change pull policy for helper pod to IfNotPresent

- deploy/chart/.helmignore
- deploy/chart/Chart.yaml
- deploy/chart/README.md
- deploy/chart/templates/NOTES.txt
- deploy/chart/templates/_helpers.tpl
- deploy/chart/templates/clusterrole.yaml
- deploy/chart/templates/clusterrolebinding.yaml
- deploy/chart/templates/configmap.yaml
- deploy/chart/templates/deployment.yaml
- deploy/chart/templates/serviceaccount.yaml
- deploy/chart/templates/storageclass.yaml
- deploy/chart/values.yaml
This PR adds a Helm chart in `deploy/chart`.
> Add Helm chart

- deploy/chart/Chart.yaml
> chart: Allow suffix for Kubernetes version detection

- deploy/chart/templates/clusterrole.yaml
- deploy/chart/templates/clusterrolebinding.yaml
- deploy/chart/templates/deployment.yaml
- deploy/local-path-storage.yaml
- deploy/provisioner.yaml
Signed-off-by: Tamal Saha <tamal@appscode.com>
> Use non-deprecated api groups

- deploy/update_image.sh
> deploy: Add update_image.sh

- deploy/chart/Chart.yaml
- deploy/chart/README.md
- deploy/chart/values.yaml
- deploy/local-path-storage.yaml
- deploy/provisioner.yaml
> Local Path Provisioner v0.0.10 release

- deploy/chart/Chart.yaml
- deploy/chart/README.md
- deploy/chart/values.yaml
- deploy/local-path-storage.yaml
- deploy/provisioner.yaml
Thanks to @dittos for fixing the leaking `tick`.
> Local Path Provisioner v0.0.14 release

- deploy/chart/templates/deployment.yaml
- deploy/chart/values.yaml
> Added helper image parameter to helm chart

- deploy/chart/Chart.yaml
- deploy/chart/README.md
- deploy/chart/values.yaml
- deploy/local-path-storage.yaml
- deploy/provisioner.yaml
Thanks to @nicktming, now we support customized setup/teardown scripts.
> Local Path Provisioner v0.0.15 release

- deploy/chart/README.md
- deploy/chart/templates/configmap.yaml
- deploy/chart/templates/deployment.yaml
- deploy/chart/values.yaml
- main.go
- provisioner.go
Fix configmap issue in v0.0.15. #108 #115
> fix configmap name hardcode

- deploy/chart/Chart.yaml
- deploy/chart/README.md
- deploy/chart/values.yaml
- deploy/local-path-storage.yaml
- deploy/provisioner.yaml
Add configmap.name option for chart installation.
> Local Path Provisioner v0.0.16 release

- deploy/chart/templates/deployment.yaml
Fix the deployment template to use the configMap name provided by helm values.
> Fix helm chart

- deploy/chart/Chart.yaml
- deploy/chart/README.md
- deploy/chart/values.yaml
- deploy/local-path-storage.yaml
- deploy/provisioner.yaml
Thanks to @rxbn, we've fixed an issue with Helm Chart deployment.
> Local Path Provisioner v0.0.17 release

- deploy/chart/templates/_helpers.tpl
- deploy/chart/templates/deployment.yaml
- deploy/chart/templates/registry-secret.yaml
- deploy/chart/templates/serviceaccount.yaml
- deploy/chart/values.yaml
- main.go
- provisioner.go
Trying to pass a pullsecret for the helper image.
Should help #84
> add helper pull secret

- README.md
> doc: move the configmap reference to a new section

- deploy/chart/templates/serviceaccount.yaml
fix the usage of template (and not include) in serviceaccount.yaml
fix a small ref in sa name (use template)
> Add any imagepullsecrets to serviceaccount

- main.go
Fixes #120 - needed for k3s 1.19 release
> Update helper image to point at Rancher-mirrored busybox

- README.md
- debug/config.yaml
- deploy/chart/README.md
- deploy/chart/templates/clusterrole.yaml
- deploy/chart/templates/configmap.yaml
- deploy/chart/values.yaml
- deploy/example-config.yaml
- deploy/local-path-storage.yaml
- examples/quota/Dockerfile
- examples/quota/README.md
- examples/quota/debug.yaml
- examples/quota/helper-pod.yaml
- examples/quota/setup
- examples/quota/teardown
- go.mod
- main.go
- provisioner.go
- util.go
> make helper pod configurable 

- go.mod
- go.sum
- provisioner.go
- vendor/github.com/satori/go.uuid/.travis.yml
- vendor/github.com/satori/go.uuid/LICENSE
- vendor/github.com/satori/go.uuid/README.md
- vendor/github.com/satori/go.uuid/codec.go
- vendor/github.com/satori/go.uuid/generator.go
- vendor/github.com/satori/go.uuid/sql.go
- vendor/github.com/satori/go.uuid/uuid.go
- vendor/modules.txt
To fix the race condition caused by reusing the helper pod's name.
https://github.com/rancher/local-path-provisioner/issues/154
> Add a random suffix to the helper pod's name

- deploy/chart/Chart.yaml
- deploy/chart/README.md
- deploy/chart/values.yaml
- deploy/local-path-storage.yaml
- deploy/provisioner.yaml
Fixed the helper pod race condition for multiple PVCs.
Issue: #154
> Local Path Provisioner v0.0.19 release

- .github/stale.yaml
Signed-off-by: David Ko <dko@suse.com>
> Add stale check

- provisioner.go
> Use the node label for NodeAffinity rule

- .drone.yml
Add s390x support to rancher/rancher
Part of https://github.com/rancher/rancher/issues/35501
> Add s390x arch support

- deploy/chart/Chart.yaml
- deploy/chart/README.md
- deploy/chart/values.yaml
- deploy/local-path-storage.yaml
- deploy/provisioner.yaml
> Update chart version to 0.0.21

- examples/quota/local-path-storage.yaml
> example: add local-path-provisioner with quota deploy manifest

- .drone.yml
- deploy/local-path-storage.yaml
Build master-head image for master branch's deploy manifest.
> drone: build master-head image

- .drone.yml
- deploy/chart/local-path-provisioner/Chart.yaml
- deploy/chart/local-path-provisioner/README.md
- deploy/chart/local-path-provisioner/values.yaml
- deploy/provisioner.yaml
- examples/quota/local-path-storage.yaml
1. drone: build image for each branch
2. Set the image tag to master-head in master branch
3. 
> Update drone manifest and image tag

- README.md
- deploy/chart/local-path-provisioner/Chart.yaml
- deploy/chart/local-path-provisioner/README.md
- deploy/chart/local-path-provisioner/values.yaml
- deploy/local-path-storage.yaml
- deploy/provisioner.yaml
- examples/quota/local-path-storage.yaml
> Local Path Provisioner v0.0.22 release

- deploy/chart/local-path-provisioner/templates/configmap.yaml
- deploy/chart/local-path-provisioner/values.yaml
Users can set the helper image by once now.
Signed-off-by: tgfree <tgfree7@gmail.com>
> CHG: merge helper-image setting into one place for helm charts

- package/Dockerfile
> dockerfile: always upgrade busybox and zlib

- README.md
- deploy/chart/local-path-provisioner/templates/configmap.yaml
- deploy/chart/local-path-provisioner/templates/serviceaccount.yaml
- deploy/chart/local-path-provisioner/values.yaml
- examples/pod-with-local-volume/kustomization.yaml
- examples/pod-with-local-volume/pod.yaml
- examples/pvc-with-local-volume/kustomization.yaml
- examples/pvc-with-local-volume/pvc.yaml
- examples/shared-fs/deployment.yaml
- examples/shared-fs/pvc.yaml
- package/Dockerfile
- provisioner.go
- test/pod_test.go
- test/testdata/pod-with-local-volume/kustomization.yaml
Signed-off-by: Derek Su [derek.su@suse.com](mailto:derek.su@suse.com)
> Cherry pick PRs for v0.0.23

- README.md
- deploy/chart/local-path-provisioner/Chart.yaml
- deploy/chart/local-path-provisioner/README.md
- deploy/chart/local-path-provisioner/values.yaml
- deploy/local-path-storage.yaml
- deploy/provisioner.yaml
- examples/quota/local-path-storage.yaml
> Bump to v0.0.23

- deploy/chart/local-path-provisioner/templates/configmap.yaml
Fixes https://github.com/rancher/local-path-provisioner/issues/274
> Fix sharedFilesystemPath not being available in helm deployment

- provisioner.go
Under the SELinux mode, the helper pod fails to do any flesystem operation.
> Run the container of the helper pod in privileged mode

- .drone.yml
> Disable the support of arm platform

- .drone.yml
This reverts commit 9245e6755a7506a3c26aef4ad6d354bf4af2bb0a.
> Revert "Disable the support of arm platform"

- deploy/chart/local-path-provisioner/templates/storageclass.yaml
- deploy/chart/local-path-provisioner/values.yaml
Add `storageClass.volumeBindingMode` value to helm chart.
> Add storageClass.volumeBindingMode value to helm chart

- deploy/chart/local-path-provisioner/templates/deployment.yaml
- deploy/chart/local-path-provisioner/values.yaml
Hello, thank you for this PVC driver.
This changes fix common pod-security warnings during deploy.
> Helm: add pod annotation, securityContext blocks

- README.md
failed to start container "helper-pod": Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime creat │
│ e failed: runc create failed: unable to start container process: exec: "/manager": stat /manager: no such file or directory: unknown
> Update README.md,rm /manager

- deploy/chart/local-path-provisioner/templates/deployment.yaml
fixes https://github.com/rancher/local-path-provisioner/issues/392
> Fix duplicate labels

- test/testdata/custom-path-pattern/storage-class.yaml
Retain will make the condition check in pod_test.go failed.
> test: use reclaimPolicy Delete instead

- test/pod_test.go
Temporarily disable the flaky test case and fix it later
> Temporarily disable TestPodWithMultipleStorageClasses

- deploy/chart/local-path-provisioner/templates/configmap.yaml
> Move helperPod namespace into metadata

- .github/workflows/helm-release.yml
> fix: rename workflows

- Dockerfile.dapper
- examples/distroless/Dockerfile.helper
- examples/distroless/Dockerfile.provisioner
- go.mod
> upgrade go to 1.24.6
