examples/pod-with-security-context.yaml, provisioner.go
This is a follow-up PR for #7, since https://github.com/rancher/local-path-provisioner/commit/3256bdf61b14c6b7e517ede0f56cfebeaf28e616, unfortunately, did not fully fix the issue.
The example I supplied is not ideal. It works with your fix because it uses Busybox which doesn't have group 1000 so the user runs with gid=0. I added `id` to the script which prints the following:
`uid=1000 gid=0(root) groups=0(root),1000`
Now, when I use an image that actually has a user with uid=1000, gid=1000, such as `jenkins/jenkins` it doesn't work because the user does not belong to group 0 in this case:
`uid=1000(jenkins) gid=1000(jenkins) groups=1000(jenkins)`
This fixes the issue using `0777` as Minikube does.
=> Fix permissions

main.go
When deploying this provisioner in non-default namespace, this provisioning fails with an message about missing local-path-storage. 
As per the deployment file, Namespace is passed using the string POD_NAMESPACE.  (https://github.com/rancher/local-path-provisioner/blob/master/deploy/local-path-storage.yaml#L75)
This PR is to correct the variable name used for fetching the namespace.
=> use the correct string for namespace env

.gitignore, Dockerfile.dapper, package/Dockerfile, scripts/build
1. Update Dockerfile.dapper to install Go 1.12, separate go gets for better image layer caching
2. replace ubuntu image with simple alpine base image
3. add linker flag -w for smaller binary
4. gitignore some generated files
I've tested this in a Vagrant box and it seems to work fine. Since the binary was built with CGO_ENABLED=0 already there was no need for anything else at runtime. I initially tested with `FROM scratch` but that failed since `/tmp` didn't exist (for logs), so I switched to just plain `alpine:latest`.
The Docker image goes down from ~320MB (v0.0.5) to ~30MB :smile:
=> build and packaging updates

Dockerfile.dapper
This PR should address #12. 
I have built an arm64 docker image km4rcus/local-path-provisioner:arm64
=> Add arm64 support

examples/pvc.yaml
We should specify the namespace for pvc, or users who use kube-ns will get in trouble.
(The pod has specified the namespace.)
=> should specify the namespace for pvc

deploy/local-path-storage.yaml
on air-gap mode if you use ```imagePullPolicy: Always``` kubernetes will try to downlod the image even there is no any internet connection. therefor if we will use ```imagePullPolicy: IfNotPresent``` if the image was pre-loaded it will work
please consider to confirm this PR to support air-gap
=> support deployment on air-gap

deploy/local-path-storage.yaml
Related to this bug in wrangler https://github.com/rancher/wrangler/pull/40
=> Remove namespaces from cluster scoped objects

deploy/chart/Chart.yaml, deploy/chart/README.md, deploy/chart/values.yaml, deploy/local-path-storage.yaml, deploy/provisioner.yaml
Thanks to @ibuildthecloud `rancher/local-path-provisioner` is now a
multi-arch image supporting amd64, arm64, and armv7
=> Local Path Provisioner v0.0.11 release

deploy/kustomization.yaml
To ease deployments using Kustomize.io now builtin with `kubectl >=v1.14`, a file has to be added to the deploy dir.
By adding `kustomization.yaml` one can define the Github repository as a remote base, which very much simplifies deployments:
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../demo
- github.com/rancher/local-path-provisioner/deploy
patches:
- patch-pvc-k3s.yaml
```
=> Add kustomization support for deployments

provisioner.go
As discussed in #77 
This seems deceptively simple, am I missing something? I can't seem to find any existing tests?
=> Change to provisioned path to include PVC Namespace and Claim name

deploy/chart/Chart.yaml, deploy/chart/README.md, deploy/chart/values.yaml, deploy/local-path-storage.yaml, deploy/provisioner.yaml
Thanks to @REBELinBLUE, we've changed the provisioned path to reflect
the PVC name and Namespace instead of the PV name.
=> Local Path Provisioner v0.0.13 release

provisioner.go
https://golang.org/pkg/time/#Tick
> While Tick is useful for clients that have no need to shut down the Ticker, be aware that without a way to shut it down the underlying Ticker cannot be recovered by the garbage collector; it "leaks".
It seems to fix high CPU usage issue. (#73)
=> Fix time.Tick leak

provisioner.go
Create local volumes instead of hostPath ones. Closes #85 .
This needs some documentation changes at the least.
=> Create local volumes instead of hostPath

provisioner.go
This PR proposed adding a log entry at info level to help with cases where the pod creation times out mostly due to the fact it can't pull the helper image, for any reason, but listing pods won't really show anything. On an air-tight environment where you can't pull images from an external registry, it's useful to see that the controller is attempting to created the helper image, be for creating or deleting a volume.
=> Add log entry upon helper pod creation

README.md, provisioner.go, scripts/ci, scripts/package
It breaks RKE.
Reopen: https://github.com/rancher/local-path-provisioner/issues/85
Revert: https://github.com/rancher/local-path-provisioner/pull/91
=> Revert the change of `local` volume

main.go
there is no need to use service account for debugging of out-of-cluster, while it could not start under current condition, so adding a default service account for debugging of out-of-cluster.
=> add default service account for debugging of out-of-cluster

provisioner.go
Use `type: Directory` instead of `type: DirectoryOrCreate` allows to block running workload on provisioned directories, to avoid the situations when initial storage is unmounted or broken.
docker image containing the fix:
```
kvaps/local-path-provisioner:v0.0.17-fix-137
```
fixes https://github.com/rancher/local-path-provisioner/issues/137
=> Do not create directory if not found

deploy/chart/templates/configmap.yaml
Configmap.yaml file has 2 duplicated fields (probably created by copy paste?)
This MR removes them.
=> chore: removed duplicated fields from the configmap.yaml

provisioner.go
Reverts rancher/local-path-provisioner#138
Due to it caused the following error in the RKE setup:
```
MountVolume.SetUp failed for volume "pvc-xxxx" : hostPath type check failed: /opt/local-path-provisioner/pvc-xxx is not a directory
```
And the directory indeed exists on the node.
=> Revert "Do not create directory if not found"

deploy/chart/Chart.yaml, deploy/chart/README.md, deploy/chart/values.yaml, deploy/local-path-storage.yaml, deploy/provisioner.yaml
Changelog:
1. Thanks to @nickming 's PR, we've added the ability to make the helper
pod and setup/teardown script customizable. For example, now you can
setup the local path provisioner to use quota with btrfs.
2. Thanks to @hwaastad 's PR, now the helper pod supports pull secret.
=> Local Path Provisioner v0.0.18 release

main.go
It's a very minor problem related to an error message introduced in #8740885, but I was confused.
When default configMap is used and `helperPod.yaml` is missing from the configMap, `main.go` complains about the `--config` flag instead of the `--helper-pod-file` flag.
=> Fix error message related to the helper-pod-file flag

deploy/chart/values.yaml, deploy/example-config.yaml, deploy/local-path-storage.yaml
I would like to suggest setting the _imagePullPolicy_ for the helper-pod to `IfNotPresent`.
Right now there is no image-tag given to the busybox-image, so `latest` is assumed - what implies _imagePullPolicy_ `Always` ([docs](https://kubernetes.io/docs/concepts/containers/images/#updating-images)). I've run quickly into the docker-hub-rate-limiting with that :)
=> use IfNotPresent image-pull-policy by default for helper-pod

main.go
This is a very quick fix to disable leader election that is not needed for non-replicated storage classes. This stops pod restarts because of re-elections.
=> Disable (un-needed) leader election to reduce pod restarts

deploy/chart/values.yaml, deploy/example-config.yaml, deploy/local-path-storage.yaml
Signed-off-by: aisuko <urakiny@gmail.com>
Under the offline situation, we can only use the images that were pre-load to the host. The specification of `helperPod.yaml` used the default value `imagePullPolicy` which equals `Always` will let the help pod failed to work. So, we should declare the specification of the image pull policy as `IfNotPresent`.
=> [Feat] Add  the new feature to support the air-gapped situation

debug/config.yaml, deploy/chart/templates/storageclass.yaml
By adding `allowVolumeExpansion` this will prevent errors if someone changes the PVC capacity size on an already provisioned PVC, since local-path-provisioner does not enforce disk usage anyways, it seems reasonable to allow the value to change without throwing an error.
However this will not update the status of the PVC, it'll still show the original amount. The project would need some sort of resource watch and update status to reflect status from spec.
=> indicate volume expansion is possible

deploy/chart/templates/deployment.yaml, deploy/chart/values.yaml, main.go
The 'sig-storage-lib-external-provisioner' provides an option for volume provisioning and deletion concurrency. so, I added an option like '--worker-threads' to allow users to control provisioning concurrency. Failed provision/delete threshold values are zero, so the provisioner can complete provisioning and deletion.
Please review.
=> Added options for worker threads and provisioning/deletion retry counts

provisioner.go, util.go
The helper Pod template's `data` volumeMount is merged with the defaults in order to allow users to specify the `mountPropagation` within the template.
Split from PR #166.
Closes #165.
Relates to #127.
=> Allow mountPropagation configuration by merging the helper Pod template's volumeMount

provisioner.go
Hey there, I'd like to introduce this change in an effort to circunvene agents that have [this problem](https://github.com/containerd/containerd/issues/4604) (in my case probably slow disk) that make the containers take longer time to spin up and the hardcoded 120 seconds make a few pvcs not being provisioned when the helper container takes too much time to start.
=> feat: Make command timeout configurable

README.md
I was walking through the great demo in the readme and ran into a little nit. `kubectl exec` has deprecated support for an older command format. This updates to the newer format which is also used higher up in the document. Nothing is broken but this may prevent a larger error as `kubectl` updates.
Issue example:
```sh
kagold@nuc-device:~$ kubectl exec volume-test cat /data/test
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
local-path-test
```
=> Fix depreciated kubectl instruction in README

README.md, examples/pod-with-local-volume/kustomization.yaml, examples/pod-with-local-volume/pod.yaml, examples/pvc-with-local-volume/kustomization.yaml, examples/pvc-with-local-volume/pvc.yaml, provisioner.go, test/pod_test.go, test/testdata/pod-with-local-volume/kustomization.yaml
resolve #85
Took the changes from #91 and added them to be enabled by ~~a config value~~ an annotation on the pvc. Default behavior is still to use hostPath volumes. By using an annotation, we can allow the user to create both `hostPath` and `local` volumes, instead of just locking down to one.
Made some small changes to the README, but will update the README and examples further if code changes are ok from maintainers.
=> Add option to create local volumes instead of hostPath

README.md, deploy/chart/local-path-provisioner/values.yaml, examples/shared-fs/deployment.yaml, examples/shared-fs/pvc.yaml, provisioner.go
Instead of spamming in #174 I will create another PR.
This is an attempt to bring shared file systems support.
`sharedFileSystemPath` allows the provisioner to use a filesystem that is mounted on all nodes at the same time.
In this case all access modes are supported: `ReadWriteOnce`, `ReadOnlyMany` and `ReadWriteMany` for storage claims.
In addition `volumeBindingMode: Immediate` can be used in  StorageClass definition.
Please note that `nodePathMap` and `sharedFileSystemPath` are mutually exclusive. If `sharedFileSystemPath` is used, then `nodePathMap` must be set to `[]`.
=> Support for shared filesystems

deploy/chart/local-path-provisioner/templates/serviceaccount.yaml
setting registry and no .Values.imagePullSecrets helm template error
Signed-off-by: tgfree <tgfree7@gmail.com>
=> fix: imagePullSecrets setting for serviceAccount

examples/quota/debug.yaml, examples/quota/helperPod.yaml, examples/quota/local-path-storage.yaml
fix xfs quota example, the helper pod need mount /dev.
fix https://github.com/rancher/local-path-provisioner/issues/195
=> fix quota example

README.md, provisioner.go, test/pod_test.go, test/testdata/pod-with-default-local-volume/kustomization.yaml, test/testdata/pod-with-default-local-volume/patch.yaml
We have  many `StatefulSet` workloads requiring the provisioner to create `local` volumes during provisioning. For several of these `StatefulSets`, we are unable to add the `volumeType` annotation which results in us having to use `hostPath` volumes which is unacceptable for us. Furthermore, it is tedious and error-prone to have to specify the `volumeType` annotation on every single PVC and would therefore prove useful to be able to specify a default volume type on the `StorageClass`.
I propose the addition of an annotation called `defaultVolumeType` on storage classes which will set the volume type for all volumes using that class. The annotation for the PVC can still be applied and will supersede the annotation on the storage class.
A basic example of a `StorageClass` with this …
=> Set default volume type in storage class

README.md, provisioner.go
We have multiple disks mounted on a node and depending on the type of storage requirement we want to create the local path pvc on a particular disk. Today we can specify multiple paths on a node via the `nodePathMap:` but the final path selection is random.
I propose to create multiple storage classes with a parameter of `path` that specifies the path to use. That way, using a storage class like below I can provision the storage on the right folder.
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: ssd-local-path
labels:
app.kubernetes.io/name: local-path-provisioner
helm.sh/chart: local-path-provisioner-0.0.23
app.kubernetes.io/instance: local-path-provisioner
app.kubernetes.io/version: "v0.0.23"
app.kubernetes.io/managed-by: Helm
provisioner: …
```
=> Multiple storage classes for same provisioner

provisioner.go
When a node is terminating, it is necessary to handle any leftover objects associated with that node. To accomplish this, the node name is passed as a parameter upon receiving the termination event. Currently, the code searches for a node name match within the affinity, which can be cumbersome. To simplify the filtering and handling process, I propose adding an annotation with the selected node name. This will allow for easier independent filtering and handling of objects using a separate controller.
Description of the change:
* Added the selected node name to the annotations.
* Removed redundant conversion operations.
=> feat - Node name annotation

deploy/chart/local-path-provisioner/templates/configmap.yaml, deploy/chart/local-path-provisioner/templates/deployment.yaml, deploy/chart/local-path-provisioner/templates/registry-secret.yaml, deploy/chart/local-path-provisioner/templates/serviceaccount.yaml
Usually, helm uses in two cases: 
* helm update/install
* helm template
In first case, helm sets namespace during the deploy (everything fine here).
In second, the result of helm template can be used in `fluxcd` or `kubectl apply` pipeline.
But template does not have `namespace`, which can affect the result of deployment (deploy to default namespace)
Thank you.
=> Helm: add namespace

deploy/chart/local-path-provisioner/README.md, deploy/chart/local-path-provisioner/templates/storageclass.yaml, deploy/chart/local-path-provisioner/values.yaml
This PR allows the user to set the default volume type of the storage class created by the Helm chart to either `local` or `hostPath` (default)
=> Set default volume type of storage class from Helm chart

README.md, deploy/chart/local-path-provisioner/templates/configmap.yaml, deploy/example-config.yaml, deploy/local-path-storage.yaml
I ran into a problem where the pod had filled up the PVC disk. 
As a result, the kubelet taint the node as `disk-pressure:NoSchedule`.
Once all the pods had moved out of the node, it was no longer possible to clean the disk using the local-path-provisioner.
The scheduler couldn't launch the helper-pod without pod tolerations.
Thank you.
=> Helm: add pod tolerations to the helper-pod

deploy/chart/local-path-provisioner/templates/deployment.yaml
(initial title: deployment: Adapt 'workerThreads' to be a string)
There is a check in the main.go module [1] which expects it to be a string so it can convert it into an integer. Without this, we cannot actually provide the configuration without hitting a conversion error. This should fix it.
Currently, we are working around it by provided a double quoted string "'8'".
[1]  https://github.com/rancher/local-path-provisioner/blob/4d42c70e748fed13cd66f86656e909184a5b08d2/main.go#L254-L257
=> deployment: Adapt values to be quoted when installed in templates

deploy/chart/local-path-provisioner/templates/clusterrole.yaml, deploy/local-path-storage.yaml, examples/quota/local-path-storage.yaml, provisioner.go
Given that the helper pods are so short lived, this gives us a very small window to view their logs before they're lost. I believe that saving these logs to the provisioner pod would greatly improve the observability of the system.
I've done this by implementing a function that gets called just before the helper pod is deleted which retrieves the logs and saves them to the provisioner. If an error is encountered when trying to retrieve the helper pod's logs, then the error message will be logged but the provisioning of the local storage will continue.
An example of what the provisioner's logs look like with this feature:
```
time="2023-04-12T10:04:50Z" level=info msg="Start of helper-pod-create-pvc-6a843d61-8a2a-4b7f-99fe-ea308c41f187 logs"
time="2023-04-12T10:04:50Z" level=info …
```
=> Save the helper pod logs to the provisioner logs

README.md, examples/distroless/Dockerfile.helper, examples/distroless/Dockerfile.provisioner, examples/distroless/README.md, examples/distroless/build_and_test.sh, examples/distroless/config.json, examples/distroless/go.mod, examples/distroless/helperPod.yaml, examples/distroless/kind.yaml, examples/distroless/kustomization.yaml, examples/distroless/local-path-storage.yaml, examples/distroless/main.go, examples/distroless/sts.yaml, provisioner.go
This pull request added two new configuration parameters (`setupCommand` and `teardownCommand`) for config data. Also passed `-a` argument with action type to script/command argument.
Goals.
I need to run setup and teardown action as binary because I need to run this binary in container image without base operating system (like alpine) for security reasons. This image does not contain shell and I are forced rewrite setup and teardown script in golang and pass it to image as binary. For this I need two configuration parameter and pass argument with action to binary.
I hope that pull request will be useful for community.
=> feature: Add configuretion to run setup/teardown command in helper container instead of run with script

deploy/chart/local-path-provisioner/README.md, deploy/chart/local-path-provisioner/templates/_helpers.tpl, deploy/chart/local-path-provisioner/templates/deployment.yaml, deploy/chart/local-path-provisioner/values.yaml
A value that is often in Helm charts is the `commonLabels` value, which seems to be absent from this chart. Common labels are also added to each of the pods in the deployment in this PR. 
Additionally, I changed the readme install instructions as `helm uninstall` no longer has the `--purge` flag and instead purges by default.
=> Helm: Add common labels value and update uninstall for helm 3

provisioner.go
This reverts commit bd0bc3128029ced34de5d350befeb6a941db38f0.
https://github.com/rancher/local-path-provisioner/issues/362
https://github.com/rancher/local-path-provisioner/issues/343
=> Revert "Run the container of the helper pod in privileged mode"

README.md
I copied this example and had a really rough go as a kubernetes beginner; I needed a custom storageClass for the RabbitMQ operator.
So my pods were broken for a long while, until I changed my storageClass to match the other `local-path` storageClass already enabled in my cluster. This `rancher.io/local-path` provisioner seems to be the key to an easy deployment of custom storageClasses.
=> Repair code example in storageClass description.

deploy/chart/local-path-provisioner/templates/configmap.yaml, deploy/chart/local-path-provisioner/templates/deployment.yaml, deploy/chart/local-path-provisioner/values.yaml
Piggybacking off this PR request from @runningman84: https://github.com/rancher/local-path-provisioner/pull/393 but retained the `selector.matchLabels` piece since it's not an immutable field after the release has been deployed and will actually block helm upgrades after the fact.
In addition to fixing the duplicate labels, this also adds the ability to add k8s resource requests/limits to the `busybox` helper-pod that's launched.
Tested this change locally in my environment and it's deploying and upgrading as expected with this flux `HelmRelease` manifest:
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
name: local-path-provisioner
namespace: local-path-provisioner
spec:
releaseName: local-path-provisioner
interval: 10m
chart:
spec:
chart: …
```
=> Remove duplicate labels and add ability to set helperpod resource requests/limits

README.md, deploy/chart/local-path-provisioner/templates/deployment.yaml, deploy/local-path-storage.yaml, main.go, provisioner.go, util.go
In the readme, there is a section on _reloading_ where it discusses the ability of the provisioner to be able to automatically pick up changes made to the config.
> The provisioner supports automatic configuration reloading. Users can change the configuration using kubectl apply or kubectl edit with config map local-path-config. There is a delay between when the user updates the config map and the provisioner picking it up.
I have found that, while this works for changes made to the `setup` and `teardown` scripts, when I make an update to the helper pod manifest in the config map the provisioner does not pick it up. I found that I would have to restart the provisioner for the helper pod changes to take effect.
I have implemented a watch function of the helper pod manifest, that takes the …
=> Automatic reloading of the helper pod manifest by the provisioner

README.md, deploy/chart/local-path-provisioner/README.md, deploy/chart/local-path-provisioner/templates/storageclass.yaml, deploy/chart/local-path-provisioner/values.yaml, provisioner.go
This PR implement support for configuring the name of the created volume directories using a template as requested in #302.
=> Add support for custom path patterns

examples/pvc-with-node/kustomization.yaml, examples/pvc-with-node/pvc.yaml
If you want to use the local path provisioner in a multi node environment, it is required to explicitly set the node name via an annotation. Unfortunally, this looks very undocumented to me. I needed to pull the right annotation label from the source code.
As minimal solution, I extended the examples with an example with a node name.
An extended version cloud also mention this in the README.
=> adding pvc with node name example

provisioner.go
- https://github.com/k3s-io/k3s/issues/10130
- 
The fix will provide the helper pod with more MCS categories which will fix the issue with having two pods trying to access shared files (the helper setup pod, and the helper delete pod)
=> Give the helper pod more range of MCS categories

deploy/chart/local-path-provisioner/README.md
Add `local-path-provisioner` to `./deploy/chart` in helm install commands
Fixes #387
=> Fix: Chart.yaml file is missing on helm install

.drone.yml
drone env is somehow broken. Before moving CI to GitHub Actions, disable the e2e temporarily.
=> drone: disable e2e test

deploy/chart/local-path-provisioner/templates/configmap.yaml, deploy/chart/local-path-provisioner/values.yaml
This change fixes #281 by allowing to customize specific parts of the hard coded helper pod:
- There is now the option to add annotations to the helper pod.
- You can override the pod name.
- Allow to override the namespace the helper pod runs in. By default, use the Helm release namespace.
=> Allow customizing helper pod

provisioner.go
This reverts commit c4dc309a6b28794f9c6fae6cdbbca9411d521847.
Hello @galal-hussein 
According to @js185692 feedback, the PR you contributed overrides the value in the configmap. 
You can apply the [solution](https://github.com/rancher/local-path-provisioner/issues/420#issuecomment-2166006104) instead.
=> Revert "Give the helper pod more range of MCS categories"

provisioner.go, test/pod_test.go, test/testdata/kind-cluster.yaml, test/testdata/pod-with-node-affinity/patch.yaml, test/testdata/pv-with-legacy-affinity/kustomization.yaml, test/testdata/pv-with-legacy-affinity/pv.yaml, test/util.go
As per https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#built-in-node-labels
[[[
Note:
The value of these labels is cloud provider specific and is not guaranteed to be reliable. For example, the value of kubernetes.io/hostname may be the same as the node name in some environments and a different value in other environments.
]]]
(This is a quick handwave in the direction of #413)
=> Bugfix: pvs not deleting was: Remove the assumption that a node's name == its hostname

deploy/chart/local-path-provisioner/README.md
I just ran across this issue:
```
helm install ./deploy/chart/local-path-provisioner --name local-path-storage --namespace local-path-storage
Error: unknown flag: --name
```
My PR updates the command to install the local-path-provisioner:
```
helm install local-path-storage --create-namespace --namespace local-path-storage ./deploy/chart/local-path-provisioner/
NAME: local-path-storage
LAST DEPLOYED: Tue Dec 10 12:01:52 2024
NAMESPACE: local-path-storage
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You can create a hostpath-backed persistent volume with a persistent volume claim like this:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: local-path-pvc
spec:
accessModes:
- ReadWriteOnce
storageClassName: local-path
resources:
requests:
storage: 2Gi
```
My helm version is …
=> fix: helm install command

package/Dockerfile, scripts/build
This PR includes changes to build local-path-provisioner for the PowerPC (ppc64le) architecture.
Referred https://github.com/rancher/local-path-provisioner/pull/447 for making required changes to support building for a new arch.
=> Build local-path-provisioner for ppc64le

provisioner.go
when saving helper logs, there is no need to create a new kubeClient. Just use the existing one in provisioner
=> use existing kubeClient when saving helper logs

deploy/chart/local-path-provisioner/templates/deployment.yaml, deploy/chart/local-path-provisioner/values.yaml, main.go
We are running into rate limits and need a way to configure the client burst and qps settings.
In our use case, we spin up GitLab and GitHub jobs in their own pods. It's not uncommon for a job to kick off multiple downstream jobs, each of which needs a PVC. Once the client-side limit is reached, jobs begin queueing, resulting in a poor experience for our users.
This PR allows overriding these settings from the defaults.
It looks like we aren’t the only ones who need to adjust these settings — see #417.
=> Allow overriding kubeclient burst and qps settings

provisioner.go
Currently, helperPod tolerates any taints as the provisioner always adds `- operator: Exists` toleration to the helperPod spec. This toleration is extremely permissive, defeating the purpose of setting extra helperPod tolerations through the config. 
This PR address the issue with the following:
1. Do not apply the default tolerations if helperPod tolerations are provided through the config
2. Replace the extremely permissive toleration with:
```
tolerations:
- key: node.kubernetes.io/disk-pressure
operator: Exists
effect: NoSchedule
```
that's already used across majority of the helper-pod examples, assuming it's as a sane new default.
Fixes https://github.com/rancher/local-path-provisioner/issues/487
=> Fix helper pod tolerations

provisioner.go
We're running local-provisioner to provide local storage for CI runners where nodes come and go pretty frequently.
We observe that the provisioner is trying run clean up on nodes that are already gone, which causes helper pods
to be stuck in pending state as they cannot be scheduled.
This PR adds a check to see if the node still exists before trying to clean up the node.
=> fix: don't try to clean up pvs on nodes that are gone
